# Usage:
# - Install pre-commit: `pip install pre-commit` (once)
# - In the main directory of QLever run: `pre-commit install`
# - Each git commit will now automatically be formatted
# - If the hook reformats files, the commit fails but files are fixed
# - Simply run `git commit` again (no need to stage changes again)
#
# TIP: To bypass pre-commit hooks (not recommended):
#   git commit --no-verify
#
# To run formatters manually without committing:
#   pre-commit run --all-files
#   clang-format -i <file>
repos:
  # Uses a packaged version of clang-format from https://github.com/ssciwr/clang-format-wheel
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
      - id: clang-format
        'types_or': [ c++, c ]

  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in .codespellrc
    rev: v2.2.6
    hooks:
    - id: codespell
