add_subdirectory(data)

addLinkAndDiscoverTest(ParallelBufferTest parser)
addLinkAndDiscoverTest(LiteralOrIriTest engine)
addLinkAndDiscoverTest(PayloadVariablesTest engine)
addLinkAndDiscoverTest(QuadTest engine)
addLinkAndDiscoverTest(BlankNodeExpressionTest engine)
addLinkAndDiscoverTest(PropertyPathTest parser)
addLinkAndDiscoverTest(UpdateTriplesTest parser)
addLinkAndDiscoverTest(NamedCachedResultTest parser)
addLinkAndDiscoverTest(DatalogRuleTest parser)
addLinkAndDiscoverTest(DatalogParserTest parser)
addLinkAndDiscoverTest(SparqlAntlrParserTest parser engine)
addLinkAndDiscoverTest(SparqlAntlrParserUpdateTest parser engine)
addLinkAndDiscoverTest(SparqlAntlrParserExpressionTest parser sparqlExpressions engine)

