add_subdirectory(data)
add_subdirectory(shex)

addLinkAndDiscoverTest(ParallelBufferTest parser)
addLinkAndDiscoverTest(LiteralOrIriTest engine)
addLinkAndDiscoverTest(PayloadVariablesTest engine)
addLinkAndDiscoverTest(QuadTest engine)
addLinkAndDiscoverTest(BlankNodeExpressionTest engine)
addLinkAndDiscoverTest(PropertyPathTest parser)
addLinkAndDiscoverTest(UpdateTriplesTest parser)
addLinkAndDiscoverTest(NamedCachedResultTest parser)
addLinkAndDiscoverTest(ShExTest parser)
addLinkAndDiscoverTest(ShExPhase2ATest parser)
addLinkAndDiscoverTest(ShExTripleExpressionTest parser)
addLinkAndDiscoverTest(ShExShapeReferenceTest parser)
addLinkAndDiscoverTest(ShapeSerializerTest parser)
addLinkAndDiscoverTestSerial(SparqlAntlrParserTest parser engine)
addLinkAndDiscoverTestSerial(SparqlAntlrParserUpdateTest parser engine)
addLinkAndDiscoverTestSerial(SparqlAntlrParserExpressionTest parser sparqlExpressions engine)

