# EPIC 10.3 AGENT 4: ARCH-AGNOSTIC DIGEST (BIT-PARITY VALIDATION)
# CMake Module for QEMU Cross-Compilation and Bit-Parity Testing
#
# Copyright 2026, QLever Architecture Neutrality Team
#
# CRITICAL INVARIANT: ARM64 and x86_64 binaries must produce bit-identical
# results on identical inputs. This module provides cross-compilation and
# QEMU-based validation to verify architectural parity.
#
# REQUIREMENTS:
#   - qemu-aarch64 (QEMU user-mode emulator for ARM64)
#   - aarch64-linux-gnu-gcc (ARM64 cross-compiler)
#   - b3sum (BLAKE3 hashing utility)
#
# USAGE:
#   include(cmake/QemuCrossCompileValidation.cmake)
#   setup_qemu_validation()
#
# TARGETS CREATED:
#   qemu_build_aarch64      - Cross-compile for ARM64
#   qemu_test_aarch64       - Run ARM64 binary in QEMU
#   qemu_validate_bitparity - Validate bit-parity across architectures
#
# SUCCESS CRITERIA:
#   BLAKE3(ARM64_results) == BLAKE3(x86_64_results)
#   Divergence count: 0/1,000,000 kernel inputs

include(CheckCXXCompilerFlag)
include(ExternalProject)

# ==============================================================================
# DEPENDENCY DETECTION
# ==============================================================================

message(STATUS "[QEMU] Checking cross-compilation dependencies...")

# Check for QEMU user-mode emulator (aarch64)
find_program(QEMU_AARCH64_EXECUTABLE qemu-aarch64
    DOC "QEMU user-mode emulator for ARM64"
)

if(QEMU_AARCH64_EXECUTABLE)
    message(STATUS "[QEMU]   qemu-aarch64: ${QEMU_AARCH64_EXECUTABLE}")
    set(QEMU_AVAILABLE TRUE)
else()
    message(STATUS "[QEMU]   qemu-aarch64: Not found (install: apt-get install qemu-user)")
    set(QEMU_AVAILABLE FALSE)
endif()

# Check for ARM64 cross-compiler
find_program(AARCH64_GCC_EXECUTABLE aarch64-linux-gnu-gcc
    DOC "ARM64 cross-compiler (GCC)"
)

if(AARCH64_GCC_EXECUTABLE)
    message(STATUS "[QEMU]   aarch64-linux-gnu-gcc: ${AARCH64_GCC_EXECUTABLE}")
    set(CROSS_COMPILER_AVAILABLE TRUE)
else()
    message(STATUS "[QEMU]   aarch64-linux-gnu-gcc: Not found (install: apt-get install gcc-aarch64-linux-gnu)")
    set(CROSS_COMPILER_AVAILABLE FALSE)
endif()

# Check for BLAKE3 hashing utility
find_program(B3SUM_EXECUTABLE b3sum
    DOC "BLAKE3 hashing utility"
)

if(B3SUM_EXECUTABLE)
    message(STATUS "[QEMU]   b3sum: ${B3SUM_EXECUTABLE}")
    set(B3SUM_AVAILABLE TRUE)
else()
    message(STATUS "[QEMU]   b3sum: Not found (install: cargo install b3sum)")
    set(B3SUM_AVAILABLE FALSE)
endif()

# Check for FPV witness (gates Agent 4 per PATCH_7)
set(FPV_WITNESS_PATH "${PROJECT_SOURCE_DIR}/fpv_witness.receipt")
if(EXISTS "${FPV_WITNESS_PATH}")
    message(STATUS "[QEMU]   FPV witness: Found (${FPV_WITNESS_PATH})")
    set(FPV_GATE_PASSED TRUE)
else()
    message(STATUS "[QEMU]   FPV witness: Not found (Agent 2 validation pending)")
    set(FPV_GATE_PASSED FALSE)
endif()

# Overall validation readiness
if(QEMU_AVAILABLE AND CROSS_COMPILER_AVAILABLE AND B3SUM_AVAILABLE AND FPV_GATE_PASSED)
    set(QEMU_VALIDATION_READY TRUE)
    message(STATUS "[QEMU] All dependencies satisfied - bit-parity validation READY")
elseif(QEMU_AVAILABLE AND CROSS_COMPILER_AVAILABLE AND B3SUM_AVAILABLE)
    set(QEMU_VALIDATION_READY FALSE)
    message(WARNING "[QEMU] Dependencies satisfied but FPV gate not passed - validation BLOCKED")
    message(WARNING "[QEMU] Run Agent 2 FPV validation to obtain fpv_witness.receipt")
else()
    set(QEMU_VALIDATION_READY FALSE)
    message(WARNING "[QEMU] Missing dependencies - bit-parity validation DISABLED")
    if(NOT QEMU_AVAILABLE)
        message(WARNING "[QEMU]   Install QEMU: sudo apt-get install qemu-user")
    endif()
    if(NOT CROSS_COMPILER_AVAILABLE)
        message(WARNING "[QEMU]   Install cross-compiler: sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu")
    endif()
    if(NOT B3SUM_AVAILABLE)
        message(WARNING "[QEMU]   Install BLAKE3: cargo install b3sum")
    endif()
endif()

# ==============================================================================
# CROSS-COMPILATION TOOLCHAIN CONFIGURATION
# ==============================================================================

# Create ARM64 toolchain file if it doesn't exist
set(AARCH64_TOOLCHAIN_FILE "${CMAKE_CURRENT_BINARY_DIR}/cmake/toolchains/aarch64-linux-gnu.cmake")

if(CROSS_COMPILER_AVAILABLE AND NOT EXISTS "${AARCH64_TOOLCHAIN_FILE}")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/cmake/toolchains")

    file(WRITE "${AARCH64_TOOLCHAIN_FILE}" "
# ARM64 Cross-Compilation Toolchain for QEMU Bit-Parity Validation
# Generated by cmake/QemuCrossCompileValidation.cmake

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

# Cross-compiler binaries
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)

# Search paths for libraries and includes
set(CMAKE_FIND_ROOT_PATH /usr/aarch64-linux-gnu)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# ARM64-specific flags
# Note: NEON is standard on AArch64, no explicit flag needed
set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} -march=armv8-a\")
set(CMAKE_C_FLAGS \"\${CMAKE_C_FLAGS} -march=armv8-a\")

# Ensure deterministic builds (no randomness)
set(CMAKE_CXX_FLAGS \"\${CMAKE_CXX_FLAGS} -frandom-seed=42\")
set(CMAKE_C_FLAGS \"\${CMAKE_C_FLAGS} -frandom-seed=42\")
")
    message(STATUS "[QEMU] Generated ARM64 toolchain file: ${AARCH64_TOOLCHAIN_FILE}")
endif()

# ==============================================================================
# TARGET: qemu_build_aarch64 (Cross-compile for ARM64)
# ==============================================================================

if(CROSS_COMPILER_AVAILABLE)
    set(QEMU_BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}/qemu_build_aarch64")

    add_custom_target(qemu_build_aarch64
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Cross-compiling for ARM64..."
        COMMAND ${CMAKE_COMMAND}
            -DCMAKE_TOOLCHAIN_FILE=${AARCH64_TOOLCHAIN_FILE}
            -DCMAKE_BUILD_TYPE=Release
            -DUSE_PRECOMPILED_HEADERS=OFF
            -G Ninja
            -B ${QEMU_BUILD_DIR}
            -S ${PROJECT_SOURCE_DIR}
        COMMAND ${CMAKE_COMMAND} --build ${QEMU_BUILD_DIR} --target BitParityValidator
        COMMENT "Cross-compiling QLever for ARM64 (QEMU validation)"
        VERBATIM
    )

    message(STATUS "[QEMU] Target 'qemu_build_aarch64' configured")
else()
    add_custom_target(qemu_build_aarch64
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] ERROR: Cross-compiler not available"
        COMMAND ${CMAKE_COMMAND} -E false
    )
endif()

# ==============================================================================
# TARGET: qemu_test_aarch64 (Run ARM64 binary in QEMU)
# ==============================================================================

if(QEMU_AVAILABLE AND CROSS_COMPILER_AVAILABLE)
    set(QEMU_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/qemu_results")

    add_custom_target(qemu_test_aarch64
        COMMAND ${CMAKE_COMMAND} -E make_directory ${QEMU_OUTPUT_DIR}
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Running ARM64 binary in QEMU..."
        COMMAND ${QEMU_AARCH64_EXECUTABLE}
            -L /usr/aarch64-linux-gnu
            ${QEMU_BUILD_DIR}/test/qemu/BitParityValidator
            --seed=42
            --count=1000000
            --output=${QEMU_OUTPUT_DIR}/arm64_results.bin
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] ARM64 execution complete"
        DEPENDS qemu_build_aarch64
        COMMENT "Executing ARM64 binary via QEMU user-mode emulation"
        VERBATIM
    )

    message(STATUS "[QEMU] Target 'qemu_test_aarch64' configured")
else()
    add_custom_target(qemu_test_aarch64
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] ERROR: QEMU or cross-compiler not available"
        COMMAND ${CMAKE_COMMAND} -E false
    )
endif()

# ==============================================================================
# TARGET: qemu_validate_bitparity (Compare ARM64 vs x86_64 results)
# ==============================================================================

if(QEMU_VALIDATION_READY)
    add_custom_target(qemu_validate_bitparity
        # Step 1: Build and run x86_64 binary
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Step 1/4: Building x86_64 binary..."
        COMMAND ${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR} --target BitParityValidator

        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Step 2/4: Running x86_64 binary..."
        COMMAND ${CMAKE_COMMAND} -E make_directory ${QEMU_OUTPUT_DIR}
        COMMAND ${CMAKE_BINARY_DIR}/test/qemu/BitParityValidator
            --seed=42
            --count=1000000
            --output=${QEMU_OUTPUT_DIR}/x86_64_results.bin

        # Step 2: Build and run ARM64 binary via QEMU
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Step 3/4: Running ARM64 binary via QEMU..."
        COMMAND ${CMAKE_COMMAND} --build ${CMAKE_BINARY_DIR} --target qemu_test_aarch64

        # Step 3: Compute BLAKE3 digests
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] Step 4/4: Validating bit-parity..."
        COMMAND ${CMAKE_COMMAND}
            -DQEMU_OUTPUT_DIR=${QEMU_OUTPUT_DIR}
            -DB3SUM_EXECUTABLE=${B3SUM_EXECUTABLE}
            -P ${CMAKE_CURRENT_SOURCE_DIR}/cmake/scripts/validate_bitparity.cmake

        DEPENDS BitParityValidator qemu_test_aarch64
        COMMENT "Validating bit-parity: ARM64 vs x86_64 (1M kernel inputs)"
        VERBATIM
    )

    message(STATUS "[QEMU] Target 'qemu_validate_bitparity' configured")
else()
    add_custom_target(qemu_validate_bitparity
        COMMAND ${CMAKE_COMMAND} -E echo "[QEMU] ERROR: Validation not ready (missing dependencies or FPV gate)"
        COMMAND ${CMAKE_COMMAND} -E false
    )
endif()

# ==============================================================================
# VALIDATION SCRIPT (Embedded)
# ==============================================================================

# Create validation script that compares BLAKE3 digests
set(VALIDATION_SCRIPT "${CMAKE_CURRENT_BINARY_DIR}/cmake/scripts/validate_bitparity.cmake")
file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/cmake/scripts")

file(WRITE "${VALIDATION_SCRIPT}" "
# BLAKE3 Bit-Parity Validation Script
# Compares ARM64 and x86_64 results for identical digests

set(ARM64_FILE \"\${QEMU_OUTPUT_DIR}/arm64_results.bin\")
set(X86_64_FILE \"\${QEMU_OUTPUT_DIR}/x86_64_results.bin\")

# Verify files exist
if(NOT EXISTS \"\${ARM64_FILE}\")
    message(FATAL_ERROR \"ARM64 results not found: \${ARM64_FILE}\")
endif()
if(NOT EXISTS \"\${X86_64_FILE}\")
    message(FATAL_ERROR \"x86_64 results not found: \${X86_64_FILE}\")
endif()

# Compute BLAKE3 digests
execute_process(
    COMMAND \${B3SUM_EXECUTABLE} \${ARM64_FILE}
    OUTPUT_VARIABLE ARM64_HASH_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REGEX MATCH \"^[a-f0-9]+\" ARM64_DIGEST \"\${ARM64_HASH_OUTPUT}\")

execute_process(
    COMMAND \${B3SUM_EXECUTABLE} \${X86_64_FILE}
    OUTPUT_VARIABLE X86_64_HASH_OUTPUT
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
string(REGEX MATCH \"^[a-f0-9]+\" X86_64_DIGEST \"\${X86_64_HASH_OUTPUT}\")

# Display results
message(STATUS \"==============================================\")
message(STATUS \"BIT-PARITY VALIDATION RESULTS\")
message(STATUS \"==============================================\")
message(STATUS \"ARM64 digest:  \${ARM64_DIGEST}\")
message(STATUS \"x86_64 digest: \${X86_64_DIGEST}\")
message(STATUS \"---------------------------------------------\")

# Validate equality
if(\"\${ARM64_DIGEST}\" STREQUAL \"\${X86_64_DIGEST}\")
    message(STATUS \"✅ BIT-PARITY VALIDATED\")
    message(STATUS \"   Architectures: ARM64 == x86_64\")
    message(STATUS \"   Kernel inputs: 1,000,000\")
    message(STATUS \"   Divergences: 0\")
    message(STATUS \"   Digest: \${ARM64_DIGEST}\")
    message(STATUS \"==============================================\")
else()
    message(FATAL_ERROR \"
=============================================
❌ BIT-PARITY DIVERGENCE DETECTED
=============================================
ARM64 digest:  \${ARM64_DIGEST}
x86_64 digest: \${X86_64_DIGEST}

AGENT 9 REVIEW REQUIRED:
  - Check qleverest::vmath SIMD implementations
  - Verify AVX-512 and NEON produce identical results
  - Review Instruction Mask for hardware leakage

BUILD ABORTED (DivergenceAbort exit code: 42)
=============================================
\")
endif()
")

message(STATUS "[QEMU] Validation script created: ${VALIDATION_SCRIPT}")

# ==============================================================================
# SETUP FUNCTION (Public API)
# ==============================================================================

function(setup_qemu_validation)
    if(QEMU_VALIDATION_READY)
        message(STATUS "[QEMU] Bit-parity validation targets available:")
        message(STATUS "[QEMU]   make qemu_build_aarch64      - Cross-compile for ARM64")
        message(STATUS "[QEMU]   make qemu_test_aarch64       - Run ARM64 in QEMU")
        message(STATUS "[QEMU]   make qemu_validate_bitparity - Full validation")
    elseif(NOT FPV_GATE_PASSED)
        message(STATUS "[QEMU] Bit-parity validation BLOCKED by FPV gate")
        message(STATUS "[QEMU]   Run: Agent 2 FPV validation to unblock")
    else()
        message(STATUS "[QEMU] Bit-parity validation DISABLED (missing dependencies)")
    endif()
endfunction()
